In [ ]:
# https://www.geeksforgeeks.org/k-mode-clustering-in-python/

In [ ]:
# pip install kmodes

In [ ]:
# importing necessary libraries 
import pandas as pd 
import numpy as np 
# !pip install kmodes 
from kmodes.kmodes import KModes 
import matplotlib.pyplot as plt 
%matplotlib inline 
  
# Elbow curve to find optimal K 
cost = [] 
K = range(1,5) 
for k in list(K): 
    kmode = KModes(n_clusters=k, init = "random", n_init = 5, verbose=1) 
    kmode.fit_predict(data) 
    cost.append(kmode.cost_) 
      
plt.plot(K, cost, 'x-') 
plt.xlabel('No. of clusters') 
plt.ylabel('Cost') 
plt.title('Elbow Curve') 
plt.show()

In [ ]:
# Building the model with 3 clusters 
kmode = KModes(n_clusters=2, init = "random", n_init = 5, verbose=1) 
clusters = kmode.fit_predict(data) 
clusters

### Different Routine

In [ ]:
# https://www.kaggle.com/code/ashydv/bank-customer-clustering-k-modes-clustering

In [ ]:
# supress warnings
import warnings
warnings.filterwarnings('ignore')

# Importing all required packages
import numpy as np
import pandas as pd

# Data viz lib
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from matplotlib.pyplot import xticks

In [89]:
bank = pd.read_csv('C:/Users/methvenr/Documents/kmodes_list.csv', sep = '|')

In [90]:
bank.head()

,emplid,job_family_name,job_title,business_title,region,location_country_name,manager_flag,teamname,job_lvl_nm,job_tech_indicator,tenure,tenureincurrentrole,is_customerfacing
0,107802000,MKTG,General MKTG II,Program Manager,United States,USA,No,"Event Content, Field & Partner Events - Global...",L 5,Non-Tech,4 Years,1 Years,No
1,112837273,MKTG,General MKTG II,"Manager, Event Content",United States,USA,No,"Event Content, Field & Partner Events - Global...",L 5,Non-Tech,2 Years,2 Years,No
2,105755964,MKTG,"Manager III, General MKTG","Sr. Program Mgr, Event Content",United States,USA,Yes,"Event Content, Field & Partner Events - Global...",L 6,Non-Tech,5 Years,2 Years,No
3,112303207,MKTG,General MKTG II,Event Content Manager,United States,USA,No,"Event Content, Field & Partner Events - Global...",L 5,Non-Tech,2 Years,2 Years,No
4,109706857,MKTG,General MKTG II,"Content Manager, Global Events",United States,USA,Yes,"Event Content, Field & Partner Events - Global...",L 5,Non-Tech,3 Years,3 Years,No

In [ ]:
bank.columns

In [ ]:
bank_cust = bank[['job_family_name','job_title', 'business_title', 'region', 'location_country_name', 'manager_flag', 'teamname','job_lvl_nm','job_tech_indicator','tenure','tenureincurrentrole','is_customerfacing']]

In [ ]:
bank_cust = bank[['business_title', 'region', 'teamname','job_lvl_nm','tenure']]

In [ ]:
# Converting age into categorical variable.
bank_cust['age_bin'] = pd.cut(bank_cust['age'], [0, 20, 30, 40, 50, 60, 70, 80, 90, 100], 
                              labels=['0-20', '20-30', '30-40', '40-50','50-60','60-70','70-80', '80-90','90-100'])

bank_cust  = bank_cust.drop('age',axis = 1)

In [ ]:
# Checking Null values
bank_cust.isnull().sum()*100/bank_cust.shape[0]
# There are no NULL values in the dataset, hence it is clean.

In [ ]:
bank_cust = bank_cust.dropna().reset_index(drop=True)

In [ ]:
# First we will keep a copy of data
bank_cust_copy = bank_cust.copy()

In [ ]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
bank_cust = bank_cust.apply(le.fit_transform)
bank_cust.head()

In [ ]:
# Importing Libraries
from kmodes.kmodes import KModes

### Initializing with Cao

In [ ]:
km_cao = KModes(n_clusters=8, init = "Cao", n_init = 1, verbose=1)
fitClusters_cao = km_cao.fit_predict(bank_cust)

# Predicted Clusters
fitClusters_cao

clusterCentroidsDf = pd.DataFrame(km_cao.cluster_centroids_)
clusterCentroidsDf.columns = bank_cust.columns

# Mode of the clusters
clusterCentroidsDf

### Initializing with Huang

In [ ]:
km_huang = KModes(n_clusters=25, init = "Huang", n_init = 1, verbose=1)
fitClusters_huang = km_huang.fit_predict(bank_cust)

In [ ]:
# Predicted clusters
fitClusters_huang

In [ ]:
# Choosing K by comparing Cost against K
cost = []
for num_clusters in list(range(1,25)):
    kmode = KModes(n_clusters=num_clusters, init = "Cao", n_init = 1, verbose=1)
    kmode.fit_predict(bank_cust)
    cost.append(kmode.cost_)

In [ ]:
y = np.array([i for i in range(1,25,1)])
plt.plot(y,cost)

### Choosing K=3

In [ ]:
km_cao = KModes(n_clusters=15, init = "Cao", n_init = 1, verbose=1)
fitClusters_cao = km_cao.fit_predict(bank_cust)

In [ ]:
bank_cust = bank_cust_copy.reset_index()

In [ ]:
clustersDf = pd.DataFrame(fitClusters_cao)
clustersDf.columns = ['cluster_predicted']
combinedDf = pd.concat([bank_cust, clustersDf], axis = 1).reset_index()
combinedDf = combinedDf.drop(['index', 'level_0'], axis = 1)

In [ ]:
combinedDf.head()

In [ ]:
combinedDf.to_csv('C:/Users/methvenr/Documents/kmodes_clusters.csv', sep = '|')

### Cluster Identification

In [ ]:
cluster_0 = combinedDf[combinedDf['cluster_predicted'] == 0]
cluster_1 = combinedDf[combinedDf['cluster_predicted'] == 1]
cluster_2 = combinedDf[combinedDf['cluster_predicted'] == 2]
cluster_3 = combinedDf[combinedDf['cluster_predicted'] == 3]
cluster_4 = combinedDf[combinedDf['cluster_predicted'] == 4]
cluster_5 = combinedDf[combinedDf['cluster_predicted'] == 5]
cluster_6 = combinedDf[combinedDf['cluster_predicted'] == 6]
cluster_7 = combinedDf[combinedDf['cluster_predicted'] == 7]
cluster_8 = combinedDf[combinedDf['cluster_predicted'] == 8]
cluster_9 = combinedDf[combinedDf['cluster_predicted'] == 9]
cluster_10 = combinedDf[combinedDf['cluster_predicted'] == 10]
cluster_11 = combinedDf[combinedDf['cluster_predicted'] == 11]
cluster_12 = combinedDf[combinedDf['cluster_predicted'] == 12]
cluster_13 = combinedDf[combinedDf['cluster_predicted'] == 13]
cluster_14 = combinedDf[combinedDf['cluster_predicted'] == 14]

In [ ]:
cluster_0.info()

In [ ]:
cluster_1.info()

In [ ]:
cluster_2.info()

In [ ]:
cluster_3.info()

In [ ]:
cluster_4.info()

In [ ]:
cluster_5.info()

In [ ]:
cluster_6.info()

In [ ]:
cluster_7.info()

In [ ]:
cluster_8.info()

In [ ]:
cluster_9.info()

In [ ]:
cluster_10.info()

In [ ]:
cluster_11.info()

In [ ]:
cluster_12.info()

In [ ]:
cluster_13.info()

In [ ]:
cluster_14.info()

In [ ]:
# business_title
plt.subplots(figsize = (15,5))
sns.countplot(x=combinedDf['business_title'],order=combinedDf['business_title'].value_counts().index,hue=combinedDf['cluster_predicted'])
plt.show()

In [ ]:
# Marital
plt.subplots(figsize = (5,5))
sns.countplot(x=combinedDf['region'].astype(str),order=combinedDf['region'].astype(str).value_counts().index,hue=combinedDf['cluster_predicted'])
plt.show()

In [ ]:
# Education
plt.subplots(figsize = (15,5))
sns.countplot(x=combinedDf['education'],order=combinedDf['education'].value_counts().index,hue=combinedDf['cluster_predicted'])
plt.show()

In [ ]:
# Default

In [ ]:
f, axs = plt.subplots(1,3,figsize = (15,5))
sns.countplot(x=combinedDf['default'],order=combinedDf['default'].value_counts().index,hue=combinedDf['cluster_predicted'],ax=axs[0])
sns.countplot(x=combinedDf['housing'],order=combinedDf['housing'].value_counts().index,hue=combinedDf['cluster_predicted'],ax=axs[1])
sns.countplot(x=combinedDf['loan'],order=combinedDf['loan'].value_counts().index,hue=combinedDf['cluster_predicted'],ax=axs[2])

plt.tight_layout()
plt.show()

In [ ]:
f, axs = plt.subplots(1,2,figsize = (15,5))
sns.countplot(x=combinedDf['month'],order=combinedDf['month'].value_counts().index,hue=combinedDf['cluster_predicted'],ax=axs[0])
sns.countplot(x=combinedDf['day_of_week'],order=combinedDf['day_of_week'].value_counts().index,hue=combinedDf['cluster_predicted'],ax=axs[1])

plt.tight_layout()
plt.show()

In [ ]:
f, axs = plt.subplots(1,2,figsize = (15,5))
sns.countplot(x=combinedDf['poutcome'],order=combinedDf['poutcome'].value_counts().index,hue=combinedDf['cluster_predicted'],ax=axs[0])
sns.countplot(x=combinedDf['age_bin'],order=combinedDf['age_bin'].value_counts().index,hue=combinedDf['cluster_predicted'],ax=axs[1])

plt.tight_layout()
plt.show()

In [ ]:
# Above visualization can help in identification of clusters.

In [102]:
data = pd.read_csv('C:/Users/methvenr/Documents/kmodes_list.csv', sep = '|')

In [103]:
data = data.dropna()

In [104]:
data.head()

,emplid,job_family_name,job_title,business_title,region,location_country_name,manager_flag,teamname,job_lvl_nm,job_tech_indicator,tenure,tenureincurrentrole,is_customerfacing
0,107802000,MKTG,General MKTG II,Program Manager,United States,USA,No,"Event Content, Field & Partner Events - Global...",L 5,Non-Tech,4 Years,1 Years,No
1,112837273,MKTG,General MKTG II,"Manager, Event Content",United States,USA,No,"Event Content, Field & Partner Events - Global...",L 5,Non-Tech,2 Years,2 Years,No
2,105755964,MKTG,"Manager III, General MKTG","Sr. Program Mgr, Event Content",United States,USA,Yes,"Event Content, Field & Partner Events - Global...",L 6,Non-Tech,5 Years,2 Years,No
3,112303207,MKTG,General MKTG II,Event Content Manager,United States,USA,No,"Event Content, Field & Partner Events - Global...",L 5,Non-Tech,2 Years,2 Years,No
4,109706857,MKTG,General MKTG II,"Content Manager, Global Events",United States,USA,Yes,"Event Content, Field & Partner Events - Global...",L 5,Non-Tech,3 Years,3 Years,No

In [105]:
data = data.set_index('emplid')

In [ ]:
# Elbow curve to find optimal K
cost = []
K = range(1,20)
for num_clusters in list(K):
    kmode = KModes(n_clusters=num_clusters, init = "random", n_init = 5, verbose=1)
    kmode.fit_predict(data)
    cost.append(kmode.cost_)
    
plt.plot(K, cost, 'bx-')
plt.xlabel('No. of clusters')
plt.ylabel('Cost')
plt.title('Elbow Method For Optimal k')
plt.show()

In [106]:
# Building the model with 3 clusters
kmode = KModes(n_clusters=15, init = "random", n_init = 5, verbose=1)
clusters = kmode.fit_predict(data)
clusters

Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 1, iteration: 1/100, moves: 19745, cost: 319302.0
Run 1, iteration: 2/100, moves: 3031, cost: 317994.0
Run 1, iteration: 3/100, moves: 578, cost: 317859.0
Run 1, iteration: 4/100, moves: 79, cost: 317859.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 2, iteration: 1/100, moves: 19040, cost: 317348.0
Run 2, iteration: 2/100, moves: 3263, cost: 317073.0
Run 2, iteration: 3/100, moves: 56, cost: 317073.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 3, iteration: 1/100, moves: 19210, cost: 315497.0
Run 3, iteration: 2/100, moves: 2111, cost: 315386.0
Run 3, iteration: 3/100, moves: 0, cost: 315386.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 4, iteration: 1/100, moves: 20847, cost: 314505.0
Run 4, iteration: 2/100, moves: 5773, cost: 313898.0
Run 4, iteration: 3/100, moves: 2, cost: 313898.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 5, iteration: 1/100, moves: 24024, cost: 316590.0
Run 5, iteration: 2/100, moves: 7391, cost: 316531.0
Run 5, iteration: 3/100, moves: 60, cost: 316531.0
Best run was number 4

array([ 0,  6,  2, ...,  0, 11, 11], dtype=uint16)

In [107]:
data.insert(0, "Cluster", clusters, True)
data

,Cluster,job_family_name,job_title,business_title,region,location_country_name,manager_flag,teamname,job_lvl_nm,job_tech_indicator,tenure,tenureincurrentrole,is_customerfacing
emplid,,,,,,,,,,,,,
107802000,0,MKTG,General MKTG II,Program Manager,United States,USA,No,"Event Content, Field & Partner Events - Global...",L 5,Non-Tech,4 Years,1 Years,No
112837273,6,MKTG,General MKTG II,"Manager, Event Content",United States,USA,No,"Event Content, Field & Partner Events - Global...",L 5,Non-Tech,2 Years,2 Years,No
105755964,2,MKTG,"Manager III, General MKTG","Sr. Program Mgr, Event Content",United States,USA,Yes,"Event Content, Field & Partner Events - Global...",L 6,Non-Tech,5 Years,2 Years,No
112303207,6,MKTG,General MKTG II,Event Content Manager,United States,USA,No,"Event Content, Field & Partner Events - Global...",L 5,Non-Tech,2 Years,2 Years,No
109706857,0,MKTG,General MKTG II,"Content Manager, Global Events",United States,USA,Yes,"Event Content, Field & Partner Events - Global...",L 5,Non-Tech,3 Years,3 Years,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...
107802690,12,TPM,Technical Program Manager I,TPM,United States,USA,No,Global Services Security,L 4,Tech,4 Years,3 Years,No
519163,11,SYSSEC,Security Engineer III,Sr. Security Engineer,United States,USA,No,Global Services Security,L 6,Tech,13 Years,7 Years,No
102409841,0,SYSSEC,Security Engineer II,Security Engineer,United States,USA,No,Global Services Security,L 5,Tech,7 Years,3 Years,No
112762457,11,TPM,Technical Program Manager III,Sr. TPM,United States,USA,No,Global Services Security,L 6,Tech,2 Years,2 Years,No
109793303,11,SYSSEC,Security Engineer I,Security Engineer,United States,USA,No,Global Services Security,L 4,Tech,2 Years,2 Years,No